version: "3"

services:
  frontend-react:
    container_name: frontend-react
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production